apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: products-service:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: sqlite-data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: sqlite-pvc
